Update migration-dsl.js
Sqlite driver with createtable causes the following error when using a primary key:
SQLITE_ERROR: table "x" has more than one primary key.
Generated sql:
CREATE TABLE `x` (`y` INTEGER PRIMARY KEY AUTOINCREMENT , PRIMARY KEY (`y`))

monkeypatch ftw